spring.application.name=dax

spring.datasource.url=jdbc:postgresql://localhost:5432/dax
spring.datasource.username=postgres
spring.datasource.password=RIZ099099

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true